//! Stable issue identifiers for the Phase 4 grammar and reliability gate.
//!
//! These constants are deliberately kept separate from user-facing messages.  The
//! UI and future corpus tooling can branch on a code without depending on the
//! wording or locale of a review message.

pub const QUESTION_RANGE_UNPARSED: &str = "QUESTION_RANGE_UNPARSED";
pub const EXAM_ID_INVALID: &str = "EXAM_ID_INVALID";
pub const PASSAGE_CONTENT_MISSING: &str = "PASSAGE_CONTENT_MISSING";
pub const AUTHORING_SCHEMA_INVALID: &str = "AUTHORING_SCHEMA_INVALID";
pub const RUNTIME_COMPILER_FAILED: &str = "RUNTIME_COMPILER_FAILED";
pub const V1_COMPATIBILITY_COMPILER_FAILED: &str = "V1_COMPATIBILITY_COMPILER_FAILED";
pub const PHYSICAL_SHADOW_MISSING: &str = "PHYSICAL_SHADOW_MISSING";
pub const QUESTION_NUMBER_MISSING: &str = "QUESTION_NUMBER_MISSING";
pub const QUESTION_NUMBER_DUPLICATE: &str = "QUESTION_NUMBER_DUPLICATE";
pub const INSTRUCTION_SIGNATURE_UNRESOLVED: &str = "INSTRUCTION_SIGNATURE_UNRESOLVED";
pub const INSTRUCTION_PROVENANCE_MISSING: &str = "INSTRUCTION_PROVENANCE_MISSING";
pub const INSTRUCTION_SIGNATURE_EVIDENCE_MISSING: &str = "INSTRUCTION_SIGNATURE_EVIDENCE_MISSING";
pub const PROMPT_EMPTY: &str = "PROMPT_EMPTY";
pub const PROMPT_BOUNDARY_AMBIGUOUS: &str = "PROMPT_BOUNDARY_AMBIGUOUS";
pub const OPTION_RUN_INCOMPLETE: &str = "OPTION_RUN_INCOMPLETE";
pub const OPTION_ALPHABET_MISMATCH: &str = "OPTION_ALPHABET_MISMATCH";
pub const OPTION_BANK_MISSING: &str = "OPTION_BANK_MISSING";
pub const OPTION_BANK_SCOPE_AMBIGUOUS: &str = "OPTION_BANK_SCOPE_AMBIGUOUS";
pub const CARDINALITY_SLOT_MISMATCH: &str = "CARDINALITY_SLOT_MISMATCH";
pub const RESPONSE_GROUP_POLICY_MISMATCH: &str = "RESPONSE_GROUP_POLICY_MISMATCH";
pub const TASK_ID_DUPLICATE: &str = "TASK_ID_DUPLICATE";
pub const RESPONSE_GROUP_ID_DUPLICATE: &str = "RESPONSE_GROUP_ID_DUPLICATE";
pub const SLOT_ID_MISMATCH: &str = "SLOT_ID_MISMATCH";
pub const SLOT_REFERENCE_MISSING: &str = "SLOT_REFERENCE_MISSING";
pub const SLOT_GROUP_ASSIGNMENT_INVALID: &str = "SLOT_GROUP_ASSIGNMENT_INVALID";
pub const ANSWER_KEY_ORPHAN_SLOT: &str = "ANSWER_KEY_ORPHAN_SLOT";
pub const OPTION_BANK_REFERENCE_MISSING: &str = "OPTION_BANK_REFERENCE_MISSING";
pub const TASK_TYPE_SIGNATURE_MISMATCH: &str = "TASK_TYPE_SIGNATURE_MISMATCH";
pub const PROVENANCE_MISSING: &str = "PROVENANCE_MISSING";
pub const SLOT_HOST_MISSING: &str = "SLOT_HOST_MISSING";
pub const SLOT_OUTSIDE_FIGURE: &str = "SLOT_OUTSIDE_FIGURE";
pub const HOTSPOT_GEOMETRY_INVALID: &str = "HOTSPOT_GEOMETRY_INVALID";
pub const WORD_LIMIT_UNPARSED: &str = "WORD_LIMIT_UNPARSED";
pub const EXAMPLE_SCORING_CONFLICT: &str = "EXAMPLE_SCORING_CONFLICT";
pub const SCORING_POLICY_UNRESOLVED: &str = "SCORING_POLICY_UNRESOLVED";
pub const ANSWER_KEY_MISSING_SLOT: &str = "ANSWER_KEY_MISSING_SLOT";
pub const ANSWER_WORD_LIMIT_VIOLATION: &str = "ANSWER_WORD_LIMIT_VIOLATION";
pub const ANSWER_OPTION_NOT_IN_BANK: &str = "ANSWER_OPTION_NOT_IN_BANK";
pub const ASSET_REFERENCE_MISSING: &str = "ASSET_REFERENCE_MISSING";
pub const ASSET_ID_DUPLICATE: &str = "ASSET_ID_DUPLICATE";
pub const ASSET_HASH_MISMATCH: &str = "ASSET_HASH_MISMATCH";
pub const ASSET_PATH_UNSAFE: &str = "ASSET_PATH_UNSAFE";
pub const SIGNIFICANT_REGION_UNASSIGNED: &str = "SIGNIFICANT_REGION_UNASSIGNED";
